expose:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    database:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 20Gi

imagePullPolicy: IfNotPresent
imagePullSecrets:
logLevel: debug

clair:
  enabled: true
  image:
    repository: goharbor/clair-photon 
    tag: v2.1.0-v1.9.4
  replicas: 1
  httpProxy:
  httpsProxy:
  updatersInterval: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

database:
  type: internal
  internal:
    image:
      repository: goharbor/harbor-db
      tag: v1.9.4
    password: "changeit"
    nodeSelector: {}
    tolerations: []
    affinity: {}
  podAnnotations: {}
