expose:
  type: LoadBalancer

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    jobservice:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    database:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 2Gi

imagePullPolicy: IfNotPresent
imagePullSecrets:
logLevel: debug

clair:
  enabled: true
  image:
    repository: goharbor/clair-photon@sha256
    tag: a63029aa1aef910892e0e526ce7aecaef63a146aafae9ec7f66efb6adae55a8e
#    repository: goharbor/clair-photon
#    tag: dev
  replicas: 1
  httpProxy:
  httpsProxy:
  updatersInterval: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

database:
  type: internal
  internal:
    image:
      repository: goharbor/harbor-db@sha256
      tag: 8521a2ecf12e2e46e66108f79da8ddc4e94c2e1ab01ce99905fc4d5b882986db
#      repository: goharbor/harbor-db
#      tag: dev
    password: "changeit"
    nodeSelector: {}
    tolerations: []
    affinity: {}
  podAnnotations: {}
