{{ if .Values.clair.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.clair" . }}"
  {{ if hasKey .Values.expose "annotations" }}
  annotations:
    {{- range $key, $value := .Values.expose.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{ end }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - name: clair
      port: 6060
    - name: health
      port: 6061
  type: {{ .Values.expose.type }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: clair
{{ end }}
